language: objective-c

osx_image: xcode7.3

env: TERM=dumb

script: ./gradlew clean build coverage coveralls -s --scan

after_script: ./gradlew simulatorKill -s --scan

branches:
  except:
    - gh-pages

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
